AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Money Club Lamda.
Resources:
  LambdaSpringFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.moneyclub.LambdaHandler::handleRequest
      Runtime: java8
      FunctionName: spring-lamda-sample
      CodeUri: s3://spring-boot-amit1/652ae688876d4d2e629b6a53f18a6fa7
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/getcolor
    Export:
      Name: LambdaSpringJavaApp
